#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 12 11:04:07 2019

@author: dipankarbhattacharya
"""

import os
import pdb
import sys
if sys.version_info[0] < 3:
    from StringIO import StringIO
else:
    from io import StringIO
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import pandas as pd


NumRep=10
EndVal=82

col=np.arange(60,EndVal,5)
col=np.repeat(col, NumRep, axis=0)
colMat=col
for i in range(0,11):
    colMat=np.vstack((col,colMat))
    
colMat=colMat.T
colMatFlipUD=np.flipud(colMat)

colMat=np.vstack((colMat,colMatFlipUD[11:,:]))

dfcolMat=pd.DataFrame(colMat)

GenPath="/Users/dipankarbhattacharya/Documents/Spyder Python/StentResultsCompilation/StentForceTesting01_06_2019/FSPPeristalsis"                    
path=GenPath+"FSPPeristalsis/"

dfcolMat.to_csv(GenPath+'FSP_ESR_traj_40mmps_'+str(EndVal-2)+'.csv',index=False,header=False)
plt.savefig(path,dpi=300)