#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 14 17:28:56 2019

@author: dipankarbhattacharya
"""

import cv2

cap=cv2.VideoCapture(0)

cv2.startWindowThread()
try:
        
    while(True):
        
        ret,frame=cap.read()
        
        cv2.imshow('frame',frame)
        
        if cv2.waitKey(5000) & 0xFF == ord('q'):
            break
        
    
    for i in range(1,10):
        cv2.destroyAllWindows()
        cv2.waitkey(5000)
        
    cap.release()
    cap.destroyAllWindows()
    
except KeyboardInterrupt:
    cap.release()
    cap.destroyAllWindows()
    print('Bye Bye')